name: supermanager
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  provider: ^3.1.0

  sliding_up_panel: ^1.0.0

  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+1
  firebase_storage: ^3.1.3
  cloud_functions: ^0.4.2+2
  flutter_colorpicker:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

    uses-material-design: true
    assets:
    - assets/